import Link from "next/link";
import { Container } from "@/components/ui/Container";
import { WorkPageHero } from "@/components/work/WorkPageHero";
import { WorkPartnerCta } from "@/components/work/WorkPartnerCta";
import { ProgramPathwayCard } from "@/components/work/ProgramPathwayCard";
import { ProgrammeSection, Steps, PartnerOptions } from "@/components/work/ProgrammeSections";
import type { AiDigitalSkillsContent } from "@/content/work";

export function AiDigitalSkillsPage({ content: c }: { content: AiDigitalSkillsContent }) {
 return <main id="main-content">
  <WorkPageHero {...c.hero} />
  <section className="border-y border-brand-purple/15 bg-brand-purple-soft py-6"><Container><ul className="grid gap-4 text-sm font-semibold text-brand-purple sm:grid-cols-2 lg:grid-cols-4">{c.assurances.map(x => <li key={x}>{x}</li>)}</ul></Container></section>
  <ProgrammeSection eyebrow="AI Literacy & Digital Upskilling" title="Build Digital Skills That Can Be Applied and Shown." intro="AI literacy and digital literacy go beyond access to tools. Guided projects help learners use technology responsibly, respond to realistic briefs, evaluate their work and build a portfolio they can present confidently."><p className="max-w-3xl text-base leading-8 text-slate-600">These implementation-ready programmes are available for institutional and CSR partnership. Transferable capability, responsible AI use and professional application take priority over any single platform. For school-age learners building with circuits, code and physical computing, explore our <Link href="/our-work/stem-education" className="font-bold text-brand-purple underline underline-offset-4">STEM, robotics and coding programmes</Link>.</p></ProgrammeSection>
  <ProgrammeSection id="pathways" eyebrow="Two Career-Focused Pathways" title="Create for Work. Learn to Facilitate." intro="Choose practical digital employability or preparation for STEM educator and programme-facilitator opportunities." tint><div className="space-y-6">{c.pathways.map(p => <ProgramPathwayCard key={p.title} pathway={p} />)}</div></ProgrammeSection>
  <ProgrammeSection id="learning-model" eyebrow="Portfolio-Based Learning" title="From a Brief to Work You Can Present." intro="Each pathway works towards a portfolio of practical outputs, with feedback and revision built into the learning process."><Steps items={[["Learn", "Understand the brief, audience and tool."], ["Create", "Make a first version through guided practice."], ["Verify", "Check facts, quality and suitability."], ["Present", "Explain choices and respond to feedback."], ["Apply", "Refine the work for a realistic purpose."]]} /></ProgrammeSection>
  <ProgrammeSection id="responsible-ai" eyebrow="Responsible AI Throughout" title="Create With Confidence. Use With Responsibility." tint><Steps items={[["Prompt Clearly", "Communicate purpose, context and expected output."], ["Question Outputs", "Recognise errors and bias; keep human judgement involved."], ["Verify Information", "Check important facts against reliable sources."], ["Protect Privacy", "Keep sensitive personal information out of prompts."], ["Create Authentically", "Personalise, improve and acknowledge AI-assisted work."]]} /><p className="mt-6 max-w-3xl text-sm leading-7 text-slate-600">Practice also covers copyright awareness, originality, online safety and responsible social-media behaviour. Tools and supervised activities are selected to suit learner age and access requirements.</p></ProgrammeSection>
  <ProgrammeSection id="showcase" eyebrow="The Showcase Model" title="Skills That Can Be Seen." intro="Planned programme finales give learners a reason to refine their work and practise presenting it."><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{["Digital portfolio presentation", "Social-impact campaign", "Small-business brand kit", "Professional profile review", "Short-form video showcase", "STEM teaching demonstration"].map((x,i) => <div key={x} className="rounded-2xl border border-brand-purple/15 bg-brand-purple-soft p-6"><span className="text-xs font-bold text-brand-purple">SHOWCASE FORMAT 0{i+1}</span><h3 className="mt-3 text-lg font-bold text-brand-navy">{x}</h3></div>)}</div><p className="mt-6 text-sm leading-7 text-slate-600">Technology-company employees can contribute as mentors, speakers or project reviewers. These are proposed showcase formats, not completed-cohort case studies.</p></ProgrammeSection>
  <ProgrammeSection id="partner" eyebrow="For Technology & CSR Partners" title="Make Practical Career Skills Accessible." tint><PartnerOptions planned enable={["Digital Career Launchpad cohorts", "STEM Educator Launchpad cohorts", "Devices, connectivity and learning access", "Employee mentorship and career interactions", "Community or small-business project briefs", "Portfolio showcases and facilitator resources"]} reporting={["Defined objectives and cohort plan", "Attendance and participation tracking", "Project and portfolio evidence", "Pre/post skill-confidence assessments", "Learner showcase outputs", "Programme documentation and completion report"]} /></ProgrammeSection>
  <WorkPartnerCta cta={c.cta} />
 </main>;
}
